### ISSUE TITLE
请问在项目中接口地址看到的bbs和img目录经从github down下之后未找到相关文件夹是什么原因？

### ISSUE THREAD

**Issue by FLASOFOT** [LmyFreeMan/question#1]
![image](https://user-images.githubusercontent.com/25561361/74583897-268d2980-5007-11ea-8922-9929e120c173.png)

**Comment by LmyFreeMan** [comment]
参照：https://github.com/LmyFreeMan/leaf/blob/master/%E5%90%8E%E5%8F%B0/bbs/application/api/controller/Index.php
